### ISSUE TITLE
iNetCDFGlobalAttribute illegal attribute

### ISSUE THREAD

**Issue by xhoenner** [aodn/talend-components#50]
@jonescc thinks this might be due to the fact that the corresponding NetCDF library hasn't been updated for a while.

Below a copy of the logs when trying to harvest the following NetCDF file through the IMAS Thredds Catalog: http://thredds.imas.utas.edu.au/thredds/dodsC/IMAS/AMcMinn_FRRF_l_Astrolabe/2009/FRRF_TSB_20091111T211528Z_FHZI_FV01_fluorometry-R02009n_END-20091116T013412Z.nc

```
yyerror: line 303 near |as|; syntax error, unexpected SCAN_WORD, expecting ';' or ','
Illegal attribute
opendap.dap.parsers.ParseException: context: ^
	at opendap.dap.parsers.Dapparse.dap_parse_error(Dapparse.java:500)
	at opendap.dap.parsers.Dapparse.daperror(Dapparse.java:487)
	at opendap.dap.parsers.DapParser.yyaction(DapParser.java:745)
	at opendap.dap.parsers.DapParser.parse(DapParser.java:1425)
	at opendap.dap.parsers.DapParser.parse(DapParser.java:1978)
	at opendap.dap.parsers.Dapparse.dapparse(Dapparse.java:115)
	at opendap.dap.parsers.Dapparse.dasparse(Dapparse.java:131)
	at opendap.dap.DAS.parse(DAS.java:137)
	at opendap.dap.DConnect2$DASCommand.process(DConnect2.java:468)
	at opendap.dap.DConnect2.openConnection(DConnect2.java:308)
	at opendap.dap.DConnect2.getDAS(DConnect2.java:455)
	at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:217)
	at ucar.nc2.dataset.NetcdfDataset.acquireDODS(NetcdfDataset.java:786)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:677)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
	at aodn_imas_fluorometry.test_0_1.test.iNetCDFGlobalAttribute_1Process(test.java:465)
	at aodn_imas_fluorometry.test_0_1.test.runJobInTOS(test.java:795)
	at aodn_imas_fluorometry.test_0_1.test.main(test.java:663)
```

Note that this doesn't throw an error, hence it doesn't compromise the integrity of harvesters.

**Comment by jonescc** [comment]
Try iOPeNDAPGlobalAttributes and see if you get the same error.  The NetCDF library uses OPeNDAP to access a netcdf file on thredds - using the OPeNDAP components is more direct.

**Comment by jonescc** [comment]
Actually get an error using that as well, with the latest NetCDF libraries.

**Comment by jonescc** [comment]
Doesn't like this attribute:

		<Attribute name="distribution_statement" type="String">
			<value>Data included in this file are provided \&quot;as is\&quot; without any warranty as to fitness for a particular purpose</value>
		</Attribute>

Not sure what the '\' is for.

**Comment by xhoenner** [comment]
hmm so what you're saying is that the files are problematic, not the Talend components then? Note that I also get a similar illegal attribute message with iNetCDFInput

**Comment by jonescc** [comment]
Yes all the netcdf components will use OPeNDAP under the covers to access netcdf files on thredds servers.  Its the OPeNDAP routines which are trying to get the xml description of the file (.ddx) and can't parse it.
